"""
Drawing Service - Handles file upload and simulated drawing analysis.

NOTE: The analyze_drawing function currently uses a SIMULATED/MOCK analysis engine.
This is intentional for the MVP. Replace the body of _perform_cv_analysis() with
actual Computer Vision / OCR model integration when available.

Integration points for future AI:
- OCR: Extract text/dimensions from drawings
- Computer Vision: Detect walls, columns, beams, doors, windows
- PyTorch/TF models: Semantic segmentation of floor plans
- LLM: Natural language description of detected elements
"""

import os
import asyncio
from sqlalchemy.orm import Session
from app.models.drawing import Drawing
from app.models.project import Project
from typing import Optional
import random
import math


def get_drawings(db: Session, project_id: int):
    return db.query(Drawing).filter(Drawing.project_id == project_id).all()


def get_drawing(db: Session, drawing_id: int) -> Optional[Drawing]:
    return db.query(Drawing).filter(Drawing.id == drawing_id).first()


def create_drawing_record(
    db: Session,
    project_id: int,
    file_name: str,
    file_path: str,
    file_type: str,
    file_size: float,
) -> Drawing:
    drawing = Drawing(
        project_id=project_id,
        file_name=file_name,
        file_path=file_path,
        file_type=file_type,
        file_size=file_size,
        upload_status="uploaded",
        analysis_status="pending",
    )
    db.add(drawing)
    db.commit()
    db.refresh(drawing)
    return drawing


def _perform_simulated_analysis(project: Project) -> dict:
    """
    SIMULATED drawing analysis engine for MVP demonstration.

    -------------------------------------------------------
    FUTURE AI INTEGRATION POINT:
    Replace this function body with actual CV/OCR pipeline:
    1. Load the drawing file from disk
    2. Run OCR to extract dimensions and annotations
    3. Run semantic segmentation to detect structural elements
    4. Return structured analysis result
    -------------------------------------------------------
    """
    area = project.built_up_area or 1200
    floors = project.floors or 1
    total_area = area * floors

    # Simulate number of rooms based on area
    rooms_count = max(2, int(total_area / 150))
    bedrooms = max(1, int(rooms_count * 0.4))
    bathrooms = max(1, int(rooms_count * 0.2))
    living_rooms = 1
    kitchens = 1
    other_rooms = max(0, rooms_count - bedrooms - bathrooms - living_rooms - kitchens)

    # Structural elements based on area
    columns = max(4, int(total_area / 100) * 2)
    beams = max(4, int(total_area / 80) * 2)
    walls_linear_meters = int(math.sqrt(total_area) * 8)
    doors = rooms_count + 2
    windows = rooms_count * 2

    # Dimensions
    approx_length = round(math.sqrt(area * 1.5), 1)
    approx_width = round(area / approx_length, 1)
    floor_height = 3.0  # meters

    return {
        "status": "completed",
        "analysis_type": "simulated",  # Flag: this is simulated, not real AI
        "note": "This analysis is generated by the MVP estimation engine. Integrate real CV/OCR model for actual drawing analysis.",
        "elements": {
            "rooms": {
                "total": rooms_count,
                "bedrooms": bedrooms,
                "bathrooms": bathrooms,
                "living_rooms": living_rooms,
                "kitchens": kitchens,
                "other": other_rooms,
            },
            "structural": {
                "columns": columns,
                "beams": beams,
                "walls_linear_meters": walls_linear_meters,
                "slabs": floors,
            },
            "openings": {
                "doors": doors,
                "windows": windows,
            },
        },
        "dimensions": {
            "total_built_up_area_sqft": total_area,
            "total_built_up_area_sqm": round(total_area * 0.0929, 2),
            "approx_length_m": approx_length,
            "approx_width_m": approx_width,
            "floor_height_m": floor_height,
            "floors": floors,
            "carpet_area_sqft": round(total_area * 0.70, 1),
        },
        "summary": {
            "project_type": project.project_type,
            "construction_type": project.construction_type or "RCC",
            "total_floors": floors,
            "total_area_sqft": total_area,
            "estimated_rooms": rooms_count,
            "structural_elements_detected": columns + beams,
        },
    }


def analyze_drawing(db: Session, drawing_id: int) -> Optional[Drawing]:
    """Trigger drawing analysis (simulated for MVP)."""
    drawing = db.query(Drawing).filter(Drawing.id == drawing_id).first()
    if not drawing:
        return None

    # Set status to processing
    drawing.analysis_status = "processing"
    db.commit()

    try:
        project = db.query(Project).filter(Project.id == drawing.project_id).first()
        result = _perform_simulated_analysis(project)
        drawing.analysis_status = "completed"
        drawing.analysis_result = result

        # Update project status
        project.status = "in_progress"
        db.commit()
        db.refresh(drawing)
        return drawing

    except Exception as e:
        drawing.analysis_status = "failed"
        db.commit()
        raise e
